name: Branch Protection

# Trigger on push events to any branch
on:
  push:
    branches:
      - '*'  # This will trigger on pushes to any branch

jobs:
  check-branch-protection:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Check prohibited branch
        run: |
          # Define the prohibited branch name(s)
          PROHIBITED_BRANCHES=("private" "solutions")
          
          # Get the current branch name
          CURRENT_BRANCH=${GITHUB_REF#refs/heads/}
          
          echo "Current branch: $CURRENT_BRANCH"
          
          # Check if current branch is in prohibited list
          for prohibited in "${PROHIBITED_BRANCHES[@]}"; do
            if [[ "$CURRENT_BRANCH" == "$prohibited" ]]; then
              echo "❌ ERROR: Direct pushes to branch '$CURRENT_BRANCH' are prohibited!"
              echo "This branch is protected and cannot receive direct pushes."
              echo "Please use a pull request to merge changes into this branch."
              exit 1
            fi
          done
          
          echo "✅ Branch '$CURRENT_BRANCH' is allowed for direct pushes."
          
      - name: Success message
        run: |
          echo "Branch protection check passed. Push is allowed."

# DOES NOT PREVENT force pushes..
# Using GH inbuilt mechanism instead